global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: peer-backend
  follow_redirects: true
  metrics_path: /api/v1/metrics
  static_configs:
  - targets:
    - backend:6700
